<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1

Subsetting: _select_
Indexing: _selecting one element_
Slicing: _selecting a range of elements_
Masking: select elements in the arrays according to certain conditions

## Exercise 2

In [29]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

mask = (np_array_2d[:,0].astype(int))%2==1
np_array_2d[mask][:,1]


array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

## Exercise 3

In [51]:
array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

array[array < 50] = -1
array[array > 50] = 1
array[array == 50] = 0 
print(array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
